[f]
label = "files"

[f.o]
label = "open file manager here"
run = "xdg-open . >/dev/null 2>&1 &"

[f.c]
label = "copy file path"
pick = "find . -maxdepth 4 -type f 2>/dev/null | fzf"
run = "printf '%s' {}"
post = "copy"

[f.C]
label = "copy full file path"
pick = "find . -maxdepth 4 -type f 2>/dev/null | fzf"
run = "realpath {}"
post = "copy"

[f.z]
label = "copy zoxide path"
pick_call = "menyy.pickers:zoxide"
run = "printf '%s' {}"
post = "copy"
